services:
  backend:
    stdin_open: ${STDIN_OPEN}
    tty: ${TTY}
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}
    depends_on:
      - db

  db:
    image: postgres:12
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
    volumes:
      # Ensure that ./frontend/node_modules does not get mounted
      - ./frontend/src:/app/src
      - ./frontend/index.html:/app/index.html
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data:
