# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.4.1'

gem 'active_model_serializers'
gem 'rails', '~> 8.0.0'

gem 'pg', '~> 1.1'

gem 'puma', '~> 5.0'

gem 'bootsnap', '>= 1.4.4', require: false

gem 'rack-cors'

gem 'oj_serializers'
gem 'types_from_serializers'

group :development, :test do
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'factory_bot_rails'
  gem 'rspec-rails'
end

group :development do
  gem 'listen', '~> 3.3'
  gem 'rubocop', require: false
  gem 'rubocop-rails', require: false
  gem 'rubocop-rspec_rails', require: false
  gem 'spring'
end

# Platform-specific gems
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
